# Generated by Django 5.0.1 on 2024-01-21 01:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='show',
            field=models.ManyToManyField(to='viewer.showsector'),
        ),
    ]
