# Generated by Django 5.0.1 on 2024-01-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_showsector_product_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='show',
            field=models.ManyToManyField(blank=True, to='viewer.showsector'),
        ),
    ]
